version: "3.7"

services:
  web01:
    build:
      context: .
    command: "./wait-for-it.sh db:5432 -- 'python manage.py migrate && gunicorn rinhabackend.wsgi:application --bind 0.0.0.0:8000'"
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  db:
     image: postgres
     env_file: .env
     ports:
       - "5432:5432"
     volumes:
       - .dbdata:/var/lib/postgres
