version: "3.9"

services:
  web01: &web01
    image: eduardocpdev/rinhabackend2024:latest
    build:
      context: .
    command: "./wait-for-it.sh db:5432 -- 'python manage.py migrate && gunicorn rinhabackend.wsgi:application --bind 0.0.0.0:8000'"
    ports:
      - "8001:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "140MB"

  web02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *web01
    hostname: api02
    command: "./wait-for-it.sh db:5432 -- 'gunicorn rinhabackend.wsgi:application --bind 0.0.0.0:8000'"
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web01
      - web02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"

  db:
     image: postgres
     env_file: .env
     ports:
       - "5432:5432"
     volumes:
       - .dbdata:/var/lib/postgres
     deploy:
       resources:
         limits:
           cpus: "0.40"
           memory: "250MB"
